CREATE DATABASE service_station;
USE service_station;

CREATE TABLE service_stations(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(100) DEFAULT NULL,
	CONTACT VARCHAR(10) DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE employees(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	AGE INT DEFAULT NULL,
	CONTACT VARCHAR(10) DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE customers(
	ID VARCHAR(20) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	AGE INT DEFAULT NULL,
	CONTACT VARCHAR(10) DEFAULT NULL,
	EMP_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (EMP_ID) REFERENCES employees(ID)
);
CREATE TABLE vehicles(
	ID VARCHAR(20) NOT NULL,
	TYPE ENUM('Car','Bike','Bus') NOT NULL,
	BRAND VARCHAR(20) DEFAULT NULL,
	COLOR VARCHAR(20) DEFAULT NULL,
	SERVICE_CHARGE FLOAT DEFAULT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE invoices(
	ID VARCHAR(20) NOT NULL,
	NAME_OF_OWNER VARCHAR(30) DEFAULT NULL,
	VEHICLE VARCHAR(20) DEFAULT NULL,
	AMOUNT_TOTAL FLOAT DEFAULT NULL,
	EMPLOYEE_ASSIGNED VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (VEHICLE) REFERENCES vehicles(ID),
	FOREIGN KEY (EMPLOYEE_ASSIGNED) REFERENCES employees(ID)
);
DROP TABLE invoices,vehicles,customers,employees,service_stations;
DROP DATABASE service_station;